spring:
  application:
    name: dataflow
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.99.100:3306/spring_cloud?useSSL=false&useUnicode=true&characterEncoding=UTF-8
  redis:
    host: 192.168.99.100

server:
  port: 9393
